framework:
    default_locale: 'en'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
                # translations/messages.fr.yaml
                Modifier: Modifier
